name: 'Set Local User Credentials'
description: 'A GitHub Action to set the username and password for a local user on a Windows machine.'

inputs:
  username:
    description: 'The username for the user.'
    required: true
  password:
    description: 'The password for the user.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set Local User Credentials
      shell: powershell
      run: |
        Set-LocalUser -Name "${{ inputs.username }}" -Password (ConvertTo-SecureString -AsPlainText "${{ inputs.password }}" -Force)
